services:
  spring-boot-app:
    build: .
    container_name: chatbot-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://team1_postgres:5432/${POSTGRES_DB:-chatbotdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-chatbot_user}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    networks:
      - ai-chatbot_default
    restart: unless-stopped

networks:
  ai-chatbot_default:
    external: true